### ISSUE TITLE
Decide optimal body chunk transfer limit

### ISSUE THREAD

**Issue by helenaalinder** [DD2497-Project-Group-1/dostroy#8]
Currently we only accept requests that send each body chunk below 100ms 🍗

**Comment by josefinnilsson** [comment]
With current settings, it's still possible to access the server with 1 kb/s upload and download speed so that's nice

**Comment by helenaalinder** [comment]
Also tried posting form when simulating _slow 3g_, and this is allowed. Closing this issue since RUDY-attacks typically send body chunks really slow, around 5s/chunk.
